# Nixpacks configuration for Railway

# Use Nix packages for base utilities
[phases.setup]
nixPkgs = ["bash", "python3", "curl", "cacert", "coreutils"]

# Install yt-dlp globally via pipx-style user bin
[phases.install]
cmds = [
  "python3 -m pip install --user --upgrade pip",
  "python3 -m pip install --user yt-dlp"
]

# Environment
[env]
NODE_ENV = "production"
# PORT is provided by Railway

# Start command (Railway overrides with startCommand in railway.json)
[start]
cmd = "node server.js"

# Healthcheck (Railway will hit /ping) 