services:
  - type: web
    name: soundclouder
    env: node
    buildCommand: |
      npm install
      pip3 install --user yt-dlp
      export PATH="$PATH:$HOME/.local/bin"
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PATH
        value: $PATH:$HOME/.local/bin 