services:
  - type: web
    name: soundclouder
    env: node
    buildCommand: |
      npm install
      echo "Installing yt-dlp globally..."
      curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /opt/render/project/src/yt-dlp
      chmod +x /opt/render/project/src/yt-dlp
      echo "Creating symlink..."
      ln -sf /opt/render/project/src/yt-dlp /opt/render/project/src/node_modules/.bin/yt-dlp
      echo "Verifying installation..."
      /opt/render/project/src/yt-dlp --version
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PATH
        value: /opt/render/project/src/node_modules/.bin:$PATH 